import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "../contexts/SessionProvider";
import { getServerSession } from "next-auth";
import nextAuthConfig from "@/lib/nextAuthConfig";
import { SocketContextProvider } from "@/contexts/SocketContext";
import ChatDataContextProvider from "@/contexts/ChatDataContext";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(nextAuthConfig);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <ChatDataContextProvider>
            <SocketContextProvider>
              {children}
            </SocketContextProvider>
          </ChatDataContextProvider>
        </SessionProvider>
        <Toaster/>
      </body>
    </html>
  );
}
